/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ocl_OCL */

#ifndef _Included_ocl_OCL
#define _Included_ocl_OCL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ocl_OCL
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ocl_OCL_sayHello
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
